from ClassicCrypto.Hill.Hill_ui import HillWidget
from ClassicCrypto.Caesar.Caesar_ui import CaesarWidget
from ClassicCrypto.Enigma.Enigma_ui import EnigmaWidget
from ClassicCrypto.Frequency_Analysis.Frequency_Analysis_ui import FAWidget
from ClassicCrypto.Monoalphabetic_Cipher.Monoalphabetic_Cipher_ui import MonoalphabeticWidget
from ClassicCrypto.Playfair.Playfair_ui import PlayfairWidget
from ClassicCrypto.Vigenere.Vigenere_ui import VigenereWidget
